import type {
  ActionRecord,
  BootstrapPayload,
  CalendarEventRecord,
  CustomerFileRecord,
  CustomerRecord,
  NoteRecord,
  QuoteRecord,
  StrategyRecord,
} from "./types.js";

export const DEMO_NOW = "2026-06-21T08:30:00.000Z";
export const DEMO_QUOTE_ID = "quote_sabine";
export const DEMO_CUSTOMER_ID = "customer_sabine";

export const bootstrapSeed: BootstrapPayload = {
  installer: {
    id: "installer_theo",
    name: "Theo Tiral",
    company: "Onboarding Demo Kunde",
    initials: "TT",
  },
  quoteIdForDemo: DEMO_QUOTE_ID,
  columns: [
    {
      id: "waiting_response",
      title: "Waiting for response",
      countLabel: "7x",
      countTone: "red",
    },
    {
      id: "specialist_partner",
      title: "To specialist partner",
      countLabel: "2x",
      countTone: "gray",
    },
    {
      id: "waiting_installation",
      title: "Waiting for installation",
      countLabel: "2x",
      countTone: "gray",
    },
    {
      id: "completed",
      title: "Completed",
      countLabel: "2x",
      countTone: "green",
    },
  ],
};

export const customerSeeds: CustomerRecord[] = [
  {
    id: DEMO_CUSTOMER_ID,
    initials: "SM",
    name: "Sabine Müller",
    email: "sabine.mueller@email.de",
    phone: "+49 4105 998231",
    address: "Sonnenberg 7, 21218 Seevetal",
    system: "Heat pump + Solar 9.6 kWp",
    quoteValue: 38400,
    leadBadge: "Hot lead",
    leadBadgeTone: "yellow",
    communicationPreference: "Email first, accepts scheduled calls",
    decisionNote:
      "Asked about CO2 reduction, monthly payment, and competitor comparison. Wants a confident but calm explanation.",
    householdNote:
      "Roof faces south-west with no shading. Existing oil heating is 18 years old and due for replacement.",
    updatedAt: "2026-06-21T07:30:00.000Z",
    buyerProfile: [
      {
        id: "environmentalist",
        name: "Environmentalist",
        strength: "Strong",
        tone: "green",
        description:
          "Quoted heat pump + solar and asked about CO2 reduction — sustainability is a primary driver.",
        evidence: [
          {
            label: "Asked about CO2 reduction on the call",
            source: "Call notes",
            icon: "sparkles",
          },
          {
            label: "Requested max-coverage solar config",
            source: "Intake form",
            icon: "clipboard",
          },
        ],
      },
      {
        id: "value_conscious",
        name: "Value-conscious",
        strength: "Moderate",
        tone: "yellow",
        description:
          'Requested a competitor comparison and flagged "monthly payment" — lead with payback over price.',
        evidence: [
          {
            label: 'Flagged "monthly payment" concern',
            source: "Call notes",
            icon: "phone",
          },
          {
            label: "Requested competitor comparison",
            source: "Competitor intel",
            icon: "lock",
          },
        ],
      },
    ],
  },
  makeCustomer("customer_nina", "Nina Krüger", "nina.krueger@email.de", "Ungarnstraße 7, 52070 Aachen", "Solar 8.2 kWp", 18889),
  makeCustomer("customer_markus", "Markus Lehmann", "markus.lehmann@email.de", "Am Lattensee 12, 86162 Augsburg", "Solar 7.8 kWp", 17539),
  makeCustomer("customer_anja", "Anja Becker", "anja.becker@email.de", "Lindenweg 14, 80331 München", "Solar + battery", 24210),
  makeCustomer("customer_klaus", "Klaus Hoffmann", "klaus.hoffmann@email.de", "Bahnhofstraße 3, 70173 Stuttgart", "Heat pump", 31420),
  makeCustomer("customer_birgit", "Birgit Wagner", "birgit.wagner@email.de", "Gartenstraße 22, 50667 Köln", "Solar 6.4 kWp", 15760),
  makeCustomer("customer_thomas", "Thomas Fischer", "thomas.fischer@email.de", "Hauptstraße 88, 60311 Frankfurt", "Solar + wallbox", 22980),
  makeCustomer("customer_paul", "Paul Fleischmann", "paul.fleischmann@email.de", "Langweiderstraße 4a, 86462 Langweid", "Solar 10.1 kWp", 26269),
  makeCustomer("customer_eva", "Eva Neumann", "eva.neumann@email.de", "Provinostraße 52, 86153 Augsburg", "Solar + battery", 21140),
  makeCustomer("customer_carsten", "Carsten Weber", "carsten.weber@email.de", "Am Mittleren Moos 48, 86167 Augsburg", "Solar 8.8 kWp", 19448),
  makeCustomer("customer_jana", "Jana Schulte", "jana.schulte@email.de", "Hofgartenstraße 18, 53113 Bonn", "Solar + battery", 27310),
  makeCustomer("customer_helena", "Helena Roth", "helena.roth@email.de", "Wiesenstraße 31, 48143 Münster", "Solar 5.5 kWp", 13898),
  makeCustomer("customer_david", "David König", "david.koenig@email.de", "Odenkirchener Straße 198, 41236 Mönchengladbach", "Heat pump", 16540),
];

export const quoteSeeds: QuoteRecord[] = [
  {
    id: DEMO_QUOTE_ID,
    customerId: DEMO_CUSTOMER_ID,
    title: "Sabine Müller",
    customerName: "Sabine Müller",
    contactLine: "Sabine Müller · sabine.mueller@email.de",
    address: "Sonnenberg 7, 21218 Seevetal",
    columnId: "waiting_response",
    ownerName: "Jonas",
    ownerAvatar: "JK",
    ownerTone: "yellow",
    value: 38400,
    sentAt: "2026-06-17T09:20:00.000Z",
    lastActionAt: "2026-06-21T07:30:00.000Z",
    quoteAgeDays: 4,
    daysSinceLastAction: 0,
    productSummary: "Heat pump + Solar 9.6 kWp",
    nextAction: {
      kind: "generate_strategy",
      label: "Generate strategy",
      tone: "blue",
    },
    strategyStale: false,
  },
  quote("quote_nina", "customer_nina", "Krüger, Nina", "waiting_response", 18889, "Generate strategy", "generate_strategy", "blue", "Clara", "CR", "green"),
  quote("quote_markus", "customer_markus", "Lehmann, Markus", "waiting_response", 17539, "Schedule call", "schedule_call", "yellow", "Jonas", "JK", "yellow", undefined, "action_markus_call", "strategy_markus"),
  quote("quote_anja", "customer_anja", "Becker, Anja", "waiting_response", 24210, "Follow up on signature", "follow_up_signature", "yellow", "Lukas", "LK", "blue", "Signature open", "action_anja_signature", "strategy_anja"),
  quote("quote_klaus", "customer_klaus", "Hoffmann, Klaus", "waiting_response", 31420, "Generate strategy", "generate_strategy", "blue", "Sophie", "SP", "yellow"),
  quote("quote_birgit", "customer_birgit", "Wagner, Birgit", "waiting_response", 15760, "Schedule call", "schedule_call", "yellow", "Clara", "CR", "green", undefined, "action_birgit_call", "strategy_birgit"),
  quote("quote_thomas", "customer_thomas", "Fischer, Thomas", "waiting_response", 22980, "Generate strategy", "generate_strategy", "blue", "Lukas", "LK", "blue"),
  quote("quote_paul", "customer_paul", "Fleischmann, Paul", "specialist_partner", 26269, "", "none", "gray", "Jonas", "JK", "yellow", "Partner review"),
  quote("quote_eva", "customer_eva", "Neumann, Eva", "specialist_partner", 21140, "", "none", "gray", "Clara", "CR", "green", "Partner review"),
  quote("quote_carsten_install", "customer_carsten", "Weber, Carsten", "waiting_installation", 19448, "", "none", "gray", "Sophie", "SP", "yellow", "Signed"),
  quote("quote_jana_install", "customer_jana", "Schulte, Jana", "waiting_installation", 27310, "", "none", "gray", "Jonas", "JK", "yellow", "Signed"),
  quote("quote_helena_done", "customer_helena", "Roth, Helena", "completed", 13898, "", "none", "gray", "Clara", "CR", "green", "Signed"),
  quote("quote_david_done", "customer_david", "König, David", "completed", 16540, "", "none", "gray", "Lukas", "LK", "blue", "Signed"),
];

export const strategySeeds: StrategyRecord[] = [
  {
    id: "strategy_markus",
    quoteId: "quote_markus",
    generatedAt: "2026-06-19T11:40:00.000Z",
    stale: false,
    headline: "Markus needs a short payback call before the offer goes cold.",
    summary:
      "The quote was opened twice, but the only reply was about monthly cost. The best move is not a discount email; it is a scheduled call that converts price anxiety into a payback discussion.",
    currentActionId: "action_markus_call",
    steps: [
      strategyStep(
        "step_payback_email",
        1,
        "Frame value",
        "Send payback comparison",
        "Completed after Markus asked whether the battery was worth it.",
        "Send Email",
        "completed",
        "mail",
        "Email that was sent",
        [
          "Compared self-consumption with and without battery.",
          "Showed monthly payment beside expected electricity savings.",
        ],
        "Quote reply",
        "2026-06-19T13:00:00.000Z",
        "Open email",
        "View email",
      ),
      strategyStep(
        "step_call",
        2,
        "Confirm blocker",
        "Call Markus about payback concern",
        "Make sure the objection is economics, not technical trust.",
        "Phone Call",
        "active",
        "phone",
        "Call plan",
        [
          "Ask whether monthly cash flow or total payback is the real concern.",
          "Use his own consumption estimate before discussing equipment tradeoffs.",
          "Offer a simpler battery/no-battery comparison if he is still unsure.",
        ],
        "Calendar gap",
        "2026-06-22T11:00:00.000Z",
        "Call now",
        "Schedule call",
      ),
      strategyStep(
        "step_visit",
        3,
        "Remove friction",
        "Offer a short site check if trust is still low",
        "Only use this if the call surfaces house-specific uncertainty.",
        "Meeting in person",
        "upcoming",
        "mapPin",
        "Fallback visit agenda",
        ["Check meter cabinet, inverter location, and cable path.", "Leave with one decision next step."],
        "Similar deals",
        "2026-06-23T13:00:00.000Z",
        "Schedule visit",
        "Open calendar",
      ),
    ],
  },
  {
    id: "strategy_birgit",
    quoteId: "quote_birgit",
    generatedAt: "2026-06-19T15:25:00.000Z",
    stale: false,
    headline: "Birgit is warm, but needs reassurance about service and maintenance.",
    summary:
      "Her question was not about the system size; it was about what happens after installation. A call is the right next step because it lets the installer make ownership feel low-risk.",
    currentActionId: "action_birgit_call",
    steps: [
      strategyStep(
        "step_whatsapp",
        1,
        "Build confidence",
        "Send WhatsApp video from a similar installation",
        "Completed after she asked what the finished roof would look like.",
        "Send WhatsApp Video Message",
        "completed",
        "fileText",
        "Video message that was sent",
        [
          "Showed a similar row-house roof after installation.",
          "Mentioned low visual impact and standard cable routing.",
        ],
        "Customer question",
        "2026-06-19T16:00:00.000Z",
        "Open video",
        "View video",
      ),
      strategyStep(
        "step_call",
        2,
        "Reassure",
        "Call Birgit about service coverage",
        "Answer maintenance questions before they become delay reasons.",
        "Phone Call",
        "active",
        "phone",
        "Call plan",
        [
          "Start with her maintenance question, not the quote total.",
          "Explain monitoring, warranty handling, and who to call after installation.",
          "Ask if anything else would stop her from confirming the offer this week.",
        ],
        "Customer replied",
        "2026-06-22T14:00:00.000Z",
        "Call now",
        "Schedule call",
      ),
      strategyStep(
        "step_final",
        3,
        "Close",
        "Send service summary and signature link",
        "Use only after the maintenance concern is answered.",
        "Send Email",
        "upcoming",
        "mail",
        "Email structure",
        ["Recap service coverage.", "Confirm installation window.", "Make the signature link the only requested action."],
        "Close playbook",
        "2026-06-23T15:30:00.000Z",
        "Send summary",
        "Draft email",
      ),
    ],
  },
  {
    id: "strategy_anja",
    quoteId: "quote_anja",
    generatedAt: "2026-06-18T09:10:00.000Z",
    stale: false,
    headline: "Anja is past persuasion; the next step is a clean signature nudge.",
    summary:
      "The call and site visit are done, and the quote is already verbally accepted. Another broad sales message would add noise. The right move is a concise signature follow-up with the agreed installation window.",
    currentActionId: "action_anja_signature",
    steps: [
      strategyStep(
        "step_call",
        1,
        "Qualify",
        "Confirm battery priority by phone",
        "Completed before revising the final offer.",
        "Phone Call",
        "completed",
        "phone",
        "Completed call",
        ["Confirmed blackout backup was not required.", "Kept battery for evening self-consumption."],
        "Call notes",
        "2026-06-18T10:00:00.000Z",
        "View notes",
        "Open notes",
      ),
      strategyStep(
        "step_visit",
        2,
        "Validate",
        "Check inverter location on site",
        "Completed and no scope change was required.",
        "Meeting in person",
        "completed",
        "mapPin",
        "Visit result",
        ["Garage wall is suitable for inverter and battery.", "Cable path confirmed without visible facade routing."],
        "Visit notes",
        "2026-06-19T11:30:00.000Z",
        "View visit",
        "Open notes",
      ),
      strategyStep(
        "step_final",
        3,
        "Signature",
        "Follow up on signature",
        "Send the agreed offer link and restate the installation window.",
        "Send Email",
        "active",
        "send",
        "Follow-up structure",
        [
          "Thank her for confirming the technical setup.",
          "Restate the agreed installation window.",
          "Ask for signature today so procurement can reserve the slot.",
        ],
        "Verbal yes",
        "2026-06-21T16:00:00.000Z",
        "Send follow-up",
        "Draft email",
      ),
    ],
  },
];

export const actionSeeds: ActionRecord[] = [
  {
    id: "action_sabine_generate",
    quoteId: DEMO_QUOTE_ID,
    customerId: DEMO_CUSTOMER_ID,
    taskType: "Phone Call",
    title: "Generate closing strategy",
    status: "recommended",
    logPromptTitle: "Generate strategy",
    defaultLogText: "",
  },
  {
    id: "action_markus_payback_email",
    quoteId: "quote_markus",
    customerId: "customer_markus",
    strategyId: "strategy_markus",
    stepId: "step_payback_email",
    taskType: "Send Email",
    title: "Send payback comparison",
    status: "completed",
    completedAt: "2026-06-19T13:08:00.000Z",
    logPromptTitle: "Email outcome",
    defaultLogText: "Markus opened the payback comparison twice and asked for a short call.",
  },
  {
    id: "action_markus_call",
    quoteId: "quote_markus",
    customerId: "customer_markus",
    strategyId: "strategy_markus",
    stepId: "step_call",
    taskType: "Phone Call",
    title: "Call Markus about payback concern",
    status: "recommended",
    logPromptTitle: "Log call outcome",
    defaultLogText: "Markus wants a clearer monthly-payment comparison before deciding.",
  },
  {
    id: "action_birgit_whatsapp",
    quoteId: "quote_birgit",
    customerId: "customer_birgit",
    strategyId: "strategy_birgit",
    stepId: "step_whatsapp",
    taskType: "Send WhatsApp Video Message",
    title: "Send WhatsApp video from similar installation",
    status: "completed",
    completedAt: "2026-06-19T16:10:00.000Z",
    logPromptTitle: "Video outcome",
    defaultLogText: "Birgit replied positively and asked how maintenance works after installation.",
  },
  {
    id: "action_birgit_call",
    quoteId: "quote_birgit",
    customerId: "customer_birgit",
    strategyId: "strategy_birgit",
    stepId: "step_call",
    taskType: "Phone Call",
    title: "Call Birgit about service coverage",
    status: "recommended",
    logPromptTitle: "Log call outcome",
    defaultLogText: "Birgit needs reassurance about maintenance, monitoring, and support after installation.",
  },
  {
    id: "action_anja_call",
    quoteId: "quote_anja",
    customerId: "customer_anja",
    strategyId: "strategy_anja",
    stepId: "step_call",
    taskType: "Phone Call",
    title: "Confirm battery priority by phone",
    status: "completed",
    completedAt: "2026-06-18T10:18:00.000Z",
    logPromptTitle: "Call outcome",
    defaultLogText: "Anja wanted the battery for evening self-consumption, not backup power.",
  },
  {
    id: "action_anja_visit",
    quoteId: "quote_anja",
    customerId: "customer_anja",
    strategyId: "strategy_anja",
    stepId: "step_visit",
    taskType: "Meeting in person",
    title: "Check inverter location on site",
    status: "completed",
    completedAt: "2026-06-19T12:05:00.000Z",
    logPromptTitle: "Visit outcome",
    defaultLogText: "Garage wall and cable path confirmed. No scope change required.",
  },
  {
    id: "action_anja_signature",
    quoteId: "quote_anja",
    customerId: "customer_anja",
    strategyId: "strategy_anja",
    stepId: "step_final",
    taskType: "Send Email",
    title: "Follow up on signature",
    status: "recommended",
    logPromptTitle: "Signature follow-up outcome",
    defaultLogText: "Anja signed after receiving the final link and installation window.",
  },
];

export const noteSeeds: NoteRecord[] = [
  {
    id: "note_sabine_audio",
    customerId: DEMO_CUSTOMER_ID,
    type: "audio",
    title: "Transcription",
    duration: "1:24",
    transcriptStatus: "Transcribed",
    body:
      "Sabine seemed really set on the environmental side — kept asking how much CO2 she'd actually cut. She also mentioned twice that she's comparing us with another installer and is watching the monthly cost closely. Roof faces south-west, no shading, so the 9.6 kWp config should perform well.",
    authorName: "Jonas Krüger · Installer",
    authorAvatar: "JK",
    createdAt: "2026-06-21T07:14:00.000Z",
  },
  {
    id: "note_sabine_site",
    customerId: DEMO_CUSTOMER_ID,
    type: "text",
    title: "Property intake notes",
    body:
      "Existing oil heating is 18 years old and due for replacement — strong urgency. Meter cabinet has room for the inverter. Customer asked about hold-time on the quote; said she'd decide within two weeks.",
    authorName: "Jonas Krüger · Installer",
    authorAvatar: "JK",
    createdAt: "2026-06-20T14:32:00.000Z",
  },
  {
    id: "note_markus_payback",
    customerId: "customer_markus",
    type: "text",
    title: "Email reply",
    body:
      "Markus opened the payback comparison and replied that the total price is understandable, but he wants to know what the system does to his monthly cash flow before involving his partner.",
    authorName: "Jonas Krüger · Installer",
    authorAvatar: "JK",
    createdAt: "2026-06-19T13:24:00.000Z",
  },
  {
    id: "note_birgit_service",
    customerId: "customer_birgit",
    type: "text",
    title: "WhatsApp reply",
    body:
      "Birgit liked the short installation video. Her remaining concern is who handles monitoring, maintenance, and warranty questions after the installation team leaves.",
    authorName: "Clara Richter · Sales",
    authorAvatar: "CR",
    createdAt: "2026-06-19T16:22:00.000Z",
  },
  {
    id: "note_anja_visit",
    customerId: "customer_anja",
    type: "text",
    title: "Site visit summary",
    body:
      "Garage wall confirmed for inverter and battery. Cable path is acceptable without visible facade routing. Anja verbally agreed and asked for the final signature link.",
    authorName: "Lukas Klein · Installer",
    authorAvatar: "LK",
    createdAt: "2026-06-19T12:08:00.000Z",
  },
];

export const fileSeeds: CustomerFileRecord[] = [
  {
    id: "file_sabine_intake",
    customerId: DEMO_CUSTOMER_ID,
    name: "Intake form.pdf",
    type: "pdf",
    sizeLabel: "248 KB",
    summary:
      "Initial quote request: heat pump replacement, solar coverage preference, and CO2 impact questions.",
    tags: ["intake", "motivation", "co2"],
    uploadedAt: "2026-06-20T09:12:00.000Z",
    uploadedBy: "Jonas Krüger",
  },
  {
    id: "file_sabine_energy_bill",
    customerId: DEMO_CUSTOMER_ID,
    name: "Energy bill 2024.pdf",
    type: "pdf",
    sizeLabel: "612 KB",
    summary:
      "Annual electricity and oil-heating context used to frame monthly payment and payback discussion.",
    tags: ["bill", "roi", "monthly-payment"],
    uploadedAt: "2026-06-20T10:05:00.000Z",
    uploadedBy: "Jonas Krüger",
  },
  {
    id: "file_sabine_roof_photo",
    customerId: DEMO_CUSTOMER_ID,
    name: "Roof site photo.jpg",
    type: "image",
    sizeLabel: "3.1 MB",
    summary:
      "South-west facing roof photo. No obvious shading; useful if the customer asks for physical validation.",
    tags: ["roof", "site", "trust"],
    uploadedAt: "2026-06-20T14:20:00.000Z",
    uploadedBy: "Jonas Krüger",
  },
  {
    id: "file_markus_payback",
    customerId: "customer_markus",
    name: "Payback comparison.pdf",
    type: "pdf",
    sizeLabel: "184 KB",
    summary:
      "Battery/no-battery comparison sent before Markus asked for a monthly cash-flow call.",
    tags: ["payback", "battery", "cash-flow"],
    uploadedAt: "2026-06-19T13:06:00.000Z",
    uploadedBy: "Jonas Krüger",
  },
  {
    id: "file_birgit_video_notes",
    customerId: "customer_birgit",
    name: "Similar installation notes.pdf",
    type: "pdf",
    sizeLabel: "320 KB",
    summary:
      "Reference installation notes used to reassure Birgit about appearance and service coverage.",
    tags: ["visual-proof", "service", "aftercare"],
    uploadedAt: "2026-06-19T16:03:00.000Z",
    uploadedBy: "Clara Richter",
  },
  {
    id: "file_anja_visit",
    customerId: "customer_anja",
    name: "Site validation checklist.pdf",
    type: "pdf",
    sizeLabel: "276 KB",
    summary:
      "Garage wall, cable path, and battery location confirmed before signature follow-up.",
    tags: ["visit", "signature", "technical"],
    uploadedAt: "2026-06-19T12:07:00.000Z",
    uploadedBy: "Lukas Klein",
  },
];

export const calendarSeeds: CalendarEventRecord[] = [
  event("cal_1", "Materials", "2026-06-22T06:10:00.000Z", "2026-06-22T08:15:00.000Z", "tasks", "blue"),
  event("cal_2", "Customer call", "2026-06-22T09:00:00.000Z", "2026-06-22T10:50:00.000Z", "tasks", "green"),
  event("cal_3", "Quote review", "2026-06-22T11:00:00.000Z", "2026-06-22T12:55:00.000Z", "tasks", "blue"),
  event("cal_4", "Service report", "2026-06-23T06:30:00.000Z", "2026-06-23T08:45:00.000Z", "tasks", "green"),
  event("cal_5", "Drive time", "2026-06-22T06:15:00.000Z", "2026-06-22T08:50:00.000Z", "personal", "blue"),
  event("cal_6", "Parts pickup", "2026-06-22T10:45:00.000Z", "2026-06-22T12:20:00.000Z", "personal", "yellow"),
  event("cal_7", "Customer visit", "2026-06-22T13:10:00.000Z", "2026-06-22T15:10:00.000Z", "personal", "blue"),
  event("cal_8", "Install prep", "2026-06-22T06:20:00.000Z", "2026-06-22T08:00:00.000Z", "theo", "green"),
  event("cal_9", "Callback", "2026-06-22T09:00:00.000Z", "2026-06-22T10:10:00.000Z", "theo", "orange"),
  event("cal_10", "Site visit", "2026-06-22T12:35:00.000Z", "2026-06-22T14:00:00.000Z", "theo", "blue"),
  event("cal_11", "Maintenance", "2026-06-23T07:15:00.000Z", "2026-06-23T09:00:00.000Z", "theo", "green"),
  event("cal_12", "Warehouse", "2026-06-23T10:30:00.000Z", "2026-06-23T12:05:00.000Z", "theo", "blue"),
];

function makeCustomer(
  id: string,
  name: string,
  email: string,
  address: string,
  system: string,
  quoteValue: number,
): CustomerRecord {
  const initials = name
    .split(/[\s,-]+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? "")
    .join("");

  return {
    id,
    initials,
    name,
    email,
    phone: "+49 821 100200",
    address,
    system,
    quoteValue,
    communicationPreference: "Email",
    decisionNote: "Standard residential quote follow-up.",
    householdNote: "No special household note recorded.",
    updatedAt: DEMO_NOW,
    buyerProfile: [
      {
        id: "value_conscious",
        name: "Value-conscious",
        strength: "Moderate",
        tone: "yellow",
        description:
          "Residential quote with expected ROI questions — keep the message practical and specific.",
        evidence: [
          {
            label: "Compared system options",
            source: "Quote request",
            icon: "clipboard",
          },
          {
            label: "Needs clear next step",
            source: "Deal history",
            icon: "clock",
          },
        ],
      },
    ],
  };
}

function quote(
  id: string,
  customerId: string,
  title: string,
  columnId: QuoteRecord["columnId"],
  value: number,
  nextLabel: string,
  nextKind: QuoteRecord["nextAction"]["kind"],
  nextTone: QuoteRecord["nextAction"]["tone"],
  ownerName: string,
  ownerAvatar: string,
  ownerTone: QuoteRecord["ownerTone"],
  statusLabel?: string,
  nextActionId?: string,
  strategyId?: string,
): QuoteRecord {
  const customer = customerSeeds.find((item) => item.id === customerId);
  if (!customer) {
    throw new Error(`Missing customer seed for ${customerId}`);
  }

  return {
    id,
    customerId,
    title,
    customerName: customer.name,
    contactLine: `${customer.name} · ${customer.email}`,
    address: customer.address,
    columnId,
    ...(statusLabel ? { statusLabel, statusTone: statusLabel === "Signed" ? "blue" : "yellow" } : {}),
    ownerName,
    ownerAvatar,
    ownerTone,
    value,
    sentAt: "2026-06-17T09:20:00.000Z",
    lastActionAt: "2026-06-19T12:10:00.000Z",
    quoteAgeDays: 4,
    daysSinceLastAction: 2,
    productSummary: customer.system,
    nextAction: {
      kind: nextKind,
      label: nextLabel,
      ...(nextActionId ? { actionId: nextActionId } : {}),
      tone: nextTone,
    },
    ...(strategyId ? { strategyId } : {}),
    strategyStale: false,
  };
}

function strategyStep(
  id: string,
  number: number,
  phase: string,
  title: string,
  subtitle: string,
  taskType: StrategyRecord["steps"][number]["taskType"],
  status: StrategyRecord["steps"][number]["status"],
  icon: string,
  guideTitle: string,
  bullets: string[],
  evidenceLabel: string,
  suggestedDateTime: string,
  primaryCta: string,
  secondaryCta: string,
): StrategyRecord["steps"][number] {
  return {
    id,
    number,
    phase,
    title,
    subtitle,
    taskType,
    status,
    icon,
    guideTitle,
    bullets,
    whyChips: [{ label: evidenceLabel, source: "Deal history", icon: "clock" }],
    suggestedTime: new Intl.DateTimeFormat("en", {
      weekday: "short",
      month: "short",
      day: "numeric",
    }).format(new Date(suggestedDateTime)),
    suggestedDateTime,
    primaryCta,
    secondaryCta,
  };
}

function event(
  id: string,
  title: string,
  start: string,
  end: string,
  row: CalendarEventRecord["row"],
  color: CalendarEventRecord["color"],
): CalendarEventRecord {
  return { id, title, start, end, row, color };
}
